services:
  - type: web
    name: bot-matrix-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: BASE_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
    healthCheckPath: /api/health
